# Site settings
name: 小杭的博客
email: xiao_hang0_0@163.com
author: xiao-hang
url: 木有个人网站
resume_site: 木有简历
github: https://github.com/xiao-hang/
baseurl: ""
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xiao-hang

# Build settings
markdown: kramdown

baidu_analysis: 

